### ISSUE TITLE
Have to reset the board in order to get the connection

### ISSUE THREAD

**Issue by fllay** [micro-ROS/micro_ros_arduino#989]
## Issue template

- Hardware description: 
ARM Base Ubuntu 20.04 and OpenCR
- RTOS: 
- Installation type: 
- Version or commit hash: 
ROS2 Foxy
#### Expected behavior
Agent should connect to OpenCR whenever I run this command
`ros2 run micro_ros_agent micro_ros_agent serial --dev /dev/ttyACM0`
OpenCR is programed with the example from the library (`micro-ros_tf_publisher.ino`) 
#### Actual behavior
I have to reset the OpenCR board first before I run `ros2 run micro_ros_agent micro_ros_agent serial --dev /dev/ttyACM0` otherwise I will not get the connection. Also, after I power the OpenCR for a while, it will enter the error_loop since the LED blinks. Moreover, once I got the connection and then I terminated `ros2 run micro_ros_agent micro_ros_agent serial --dev /dev/ttyACM0` using Ctrl-C. I cannot get new connection anymore unless I reset the OpenCR again.

**Comment by pablogs9** [comment]
Hello @fllay, the client will try to connect to the agent in `rclc_support_init()` for a [certain amount of times](https://github.com/eProsima/Micro-XRCE-DDS-Client/blob/243b16b659f1b46e6678db21c30f246910a3b697/CMakeLists.txt#L57) with a [certain timeout](https://github.com/eProsima/Micro-XRCE-DDS-Client/blob/243b16b659f1b46e6678db21c30f246910a3b697/CMakeLists.txt#L58). 

If this attempt fails, in this example, the app will fail. You can check the return value of this function and retry until the agent is reached. You can [ping the agent](https://github.com/micro-ROS/micro_ros_arduino/blob/e85b9b47142601a72c742e1af71a0ff399b03c07/examples/micro-ros_reconnection_example/micro-ros_reconnection_example.ino#L93) in order to wait until it is available. But in general, you should handle the client-agent connection.

In your use case, if you open the agent and later the client, the client might lose all the opportunities to connect. If you open the agent and then the client, it will succeed.
